image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10.5.0
      yarn_version: 1.7.0

cache:
  - node_modules -> yarn.lock

init:
  - git config --global core.autocrlf input

install:
  - ps: |
      if ($isWindows) {
        Update-NodeJsInstallation $env:nodejs_version $env:PLATFORM
        appveyor-retry choco install yarn -y --force --no-progress --ignore-dependencies --version $env:yarn_version
      }
  - ps: |
      if ($isLinux) {
        rm -rf "$env:NVM_DIR"
        curl -fsSL https://deb.nodesource.com/setup_10.x | sudo bash -
        sudo apt-get install -y --no-install-recommends fakeroot rpm nodejs="$env:nodejs_version-1nodesource1" yarn="$env:yarn_version-1"
      }
  - node --version
  - yarn --version
  - yarn --frozen-lockfile --non-interactive

build_script:
  - yarn cross-env NODE_ENV=production ember electron:make -e production

after_build:
- ps: 7z a -bd electron-out.zip "$env:APPVEYOR_BUILD_FOLDER/electron-out"

artifacts:
- path: electron-out.zip
  name: electron-out

test: off
